[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = [
  "npm install --legacy-peer-deps --include=optional"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node working-server.js"

[variables]
NODE_ENV = "production"
