[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node railway-start.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production]
variables = {
  NODE_ENV = "production",
  JWT_SECRET = "your-production-jwt-secret-change-this",
  SESSION_SECRET = "your-production-session-secret-change-this"
}
