[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start:production"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[variables]
NODE_ENV = "production"
PORT = "3000"
