[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node railway-simple-server.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 15
watchdogTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 1

[environments.production]
variables = {
  NODE_ENV = "production",
  JWT_SECRET = "your-production-jwt-secret-change-this",
  SESSION_SECRET = "your-production-session-secret-change-this"
}
