[build]
builder = "dockerfile"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[variables]
NODE_ENV = "production"
PORT = "3000"
